version: '3.8'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      command: ['start-dev --import-realm']
      environment:
        - KC_DB=postgres
        - KC_DB_URL_HOST=postgres_db
        - KC_DB_USERNAME=postgres
        - KC_DB_PASSWORD=password
        - KEYCLOAK_ADMIN=keycloak
        - KEYCLOAK_ADMIN_PASSWORD=password
        - KC_HTTP_PORT=9080
        - KC_HTTPS_PORT=9443
      volumes:
        - ./keycloak-config:/opt/keycloak/data/import
      ports:
        - 9080:9080
        - 9443:9443
      # depends_on:
      #   - postgres_db