version: '3.8'

services:
  postgres_db:
    image: postgres:latest # use latest official postgres version
    container_name: postgres
    environment:
      POSTGRES_DB: bookstore # database name
      POSTGRES_USER: postgres # database admin user
      POSTGRES_PASSWORD: password # database admin password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres
      - $PWD/postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data: # named volumes can be managed easier using docker-compose