apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: bookstore
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres